apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
spec:
  type: NodePort
  selector:
    app: podinfo
  ports:
  - protocol: TCP
    nodePort: {{NODE_PORT}}
    port: 4444
    targetPort: 4444
